In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros([3])

array([0., 0., 0.])

In [11]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones([3])

array([1., 1., 1.])

In [14]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,30)

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.71193554, 0.8510411 , 0.71644419, 0.93606777, 0.4657277 ])

In [21]:
np.random.rand(5,5)

array([[0.36535635, 0.27691604, 0.41963072, 0.49279707, 0.63371483],
       [0.93733128, 0.06224463, 0.33446247, 0.60974811, 0.21446068],
       [0.15472781, 0.25721068, 0.27959995, 0.35527199, 0.37104004],
       [0.5759741 , 0.56431576, 0.26651738, 0.49912629, 0.54018122],
       [0.89334659, 0.47118124, 0.00772718, 0.93736138, 0.6821891 ]])

In [22]:
np.random.rand(5)

array([0.63695594, 0.60486843, 0.57278849, 0.37457988, 0.6022597 ])

In [23]:
np.random.rand(2)

array([0.41304809, 0.09337974])

In [25]:
np.random.randn(4,4)

array([[ 0.54433795,  0.07004287,  1.6007958 , -0.49836755],
       [-0.50344575,  0.9376851 ,  0.78015967,  0.24112505],
       [-0.29499439,  0.00184446, -0.4142159 , -0.32341248],
       [ 0.15943284,  0.57171696,  0.5563581 ,  0.58467944]])

In [29]:
np.random.randint(1,100,20)

array([16,  6, 38, 88, 77, 85, 58, 58, 52, 89, 43, 56, 20, 30,  4, 23, 75,
       75, 70, 40], dtype=int32)

In [30]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)
ranarr

array([25, 24, 39,  0,  6, 34, 15, 10, 15, 39], dtype=int32)

In [38]:
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
ranarr.max()

np.int32(39)

In [42]:
ranarr.min()

np.int32(0)

In [43]:
ranarr.argmax()

np.int64(2)

In [44]:
ranarr.argmin()

np.int64(3)

In [45]:
arr.shape

(50,)

In [48]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
arr.shape

(50,)

In [53]:
arr.dtype

dtype('int64')

In [59]:
from numpy.random import randint

In [62]:
randint(2,10,100)

array([4, 7, 9, 2, 3, 5, 6, 2, 7, 8, 2, 4, 9, 2, 3, 2, 5, 2, 2, 2, 4, 8,
       8, 5, 6, 9, 5, 8, 6, 7, 6, 2, 7, 4, 3, 3, 7, 4, 8, 9, 4, 2, 7, 8,
       2, 9, 8, 6, 3, 5, 8, 2, 3, 5, 4, 2, 7, 6, 7, 4, 9, 9, 8, 6, 2, 7,
       5, 2, 6, 5, 4, 9, 6, 4, 4, 9, 5, 9, 7, 8, 8, 5, 3, 9, 5, 9, 5, 7,
       6, 5, 4, 3, 8, 9, 6, 2, 6, 6, 9, 5], dtype=int32)