In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[::3]

array([0, 3, 6, 9])

In [10]:
arr[0:5]=100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr_copy=arr.copy()

In [19]:
arr_copy[:]=100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[0]

array([ 5, 10, 15])

In [26]:
arr_2d[0][0]

np.int64(5)

In [27]:
arr_2d[2,1]

np.int64(40)

In [29]:
arr_2d[2][1]

np.int64(40)

In [30]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
arr = np.arange(1,11)

In [32]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
bool_arr=arr>5

In [34]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [35]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[arr<3]

array([1, 2])

In [38]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [42]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])